version: "3"

services:
    api:
        container_name: api_django_react
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        command: /start
        volumes:
            - .:/app
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        env_file:
            - .env
        depends_on:
            - postgres-db-django-react
            - redis
        networks:
            - estate-react
    
    postgres-db-django-react:
        container_name: postgresql_django_react
        image: postgres:12.0-alpine
        ports:
            - "5434:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - estate-react

    redis:
        container_name: redis_real_estate
        image: redis:5-alpine
        networks:
            - estate-react
    
    celery_worker:
        container_name: celery_real_estate
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        command: /start-celeryworker
        volumes:
            - .:/app
        env_file:
            - .env
        depends_on:
            - redis
            - postgres-db-django-react
        networks:
            - estate-react

    flower:
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        command: /start-flower
        volumes:
            - .:/app
        env_file:
            - .env
        ports:
            - "5557:5555"
        depends_on:
            - redis
            - postgres-db-django-react
        networks:
            - estate-react

    nginx:
        restart: always
        depends_on:
            - api
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        networks:
            - estate-react


networks:
    estate-react:
        driver: bridge

volumes:
    postgres_data:
    static_volume:
    media_volume: